# Generated by Django 5.2.7 on 2025-11-03 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_song_author_remove_song_playlists_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SongPlaylists',
            new_name='PlaylistSong',
        ),
    ]
