# Generated by Django 5.2.7 on 2025-10-20 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_song_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='cover',
            field=models.ImageField(default='covers/default.png', upload_to='covers/'),
        ),
    ]
