# Generated by Django 5.2.7 on 2025-10-20 12:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0003_playlist_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profilePic',
            field=models.ImageField(
                default='profile_pics/default.png', upload_to='profile_pics/'
            ),
        ),
    ]
