# Generated by Django 5.2.7 on 2025-11-03 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_songplaylists_playlistsong'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='own_song',
        ),
        migrations.AddField(
            model_name='song',
            name='authors',
            field=models.ManyToManyField(related_name='songs', to='api.userprofile'),
        ),
    ]
