# Generated by Django 5.2.7 on 2025-10-20 12:48

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_userprofile_profilepic'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='song',
            managers=[
                ('songManager', django.db.models.manager.Manager()),
            ],
        ),
    ]
