# Generated by Django 5.2.6 on 2025-09-29 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_song_file_audio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='contains',
        ),
        migrations.AddField(
            model_name='song',
            name='playlists',
            field=models.ManyToManyField(related_name='playlists', to='api.playlist'),
        ),
        migrations.AlterField(
            model_name='song',
            name='file_audio',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
