# Generated by Django 5.2.7 on 2025-10-21 14:46

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_song_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='playlist',
            managers=[
                ('playListManager', django.db.models.manager.Manager()),
            ],
        ),
    ]
