# Generated by Django 5.2.6 on 2025-09-29 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_playlist_contains_song_playlists_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='playlists',
            field=models.ManyToManyField(blank=True, related_name='playlists', to='api.playlist'),
        ),
    ]
