# Generated by Django 5.2.6 on 2025-09-29 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_song_artist_alter_song_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='file_audio',
            field=models.FileField(null=True, upload_to='uploads/'),
        ),
    ]
