# Generated by Django 5.2.6 on 2025-10-04 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_song_playlists'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='email',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='description',
            field=models.CharField(blank=True, default='Hi my name is <django.db.models.fields.CharField>', max_length=1000),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profilePic',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
