server {
  listen 80;
    server_name localhost;

    # SPA fallback per Vue Router
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        include /etc/nginx/mime.types;
        try_files $uri $uri/ /index.html;
    }
}
