# Use the official Alpine image for the check-comments stage.
FROM alpine:latest AS check-comments

WORKDIR /files

# Copy the files in which to check the comments for.
COPY .dockerignore .editorconfig .gitattributes .gitignore check-comments.sh ./
COPY **/*.css .
COPY **/*.js .
COPY .vscode/*.json .
COPY **/*.jsonc .
COPY **/*.py .
COPY **/*.toml .
COPY **/*.yaml .
COPY **/*.yml .

# Install ripgrep.
RUN apk add --no-cache ripgrep

# Run ripgrep commands for every check.
CMD ["sh", "-c", "./check-comments.sh"]
