# Use the official Python image for the development stage.
FROM python:3.14-alpine AS development
ARG APP="backend"
ARG PORT="8000"
ARG UID="988"

# Set environment variables.
# Prevents Python from writing pyc files to disk.
ENV PYTHONDONTWRITEBYTECODE=1
# Prevents Python from buffering stdout and stderr.
ENV PYTHONUNBUFFERED=1
# Activate debug mode for Django.
ENV DJANGO_DEBUG="True"
# Port for Django
ENV DJANGO_PORT=${PORT:-"8000"}

# Copy UV from the UV image.
COPY --from=ghcr.io/astral-sh/uv:latest --chown=${UID}:${UID} /uv /uvx /bin/

# Create the app directory.
RUN mkdir /${APP}
RUN chown -R ${UID}:${UID} /${APP}

# Set the working directory inside the container.
WORKDIR /${APP}

# Copy the Django project to the container.
ADD ./music_space ./music_space
COPY pyproject.toml manage.py README.md ./

# Run this command to synchronize all dependencies.
RUN ["/bin/uv", "sync", "--no-cache", "--dev", "--no-group", "prod"]

VOLUME /${APP}/db.sqlite3

# Expose the Django port.
EXPOSE ${PORT}

# Change the user.
# USER backend:backend -> Failed canonicalization of Python.

# Make the migrations.
# Run the migrations.
# Run Django’s development server.
CMD ["sh", "-c", "uv run --no-cache --dev --no-group prod music-space runserver 0.0.0.0:$DJANGO_PORT"]
