# Use the official Python image for the development stage.
FROM python:3.14-alpine AS development
ARG PORT="8000"
ARG SECRET_KEY="django-insecure-abcdef123456"
ARG UID="988"

# Set environment variables.
# Prevents Python from writing pyc files to disk.
ENV PYTHONDONTWRITEBYTECODE=1
# Prevents Python from buffering stdout and stderr.
ENV PYTHONUNBUFFERED=1
# Secret key for the Django database.
ENV SECRET_KEY=${SECRET_KEY}
# Activate debug mode for Django.
ENV DJANGO_DEBUG="True"
# Allowed hosts for Django.
ENV DJANGO_ALLOWED_HOSTS="localhost,127.0.0.1,backend"

# Copy UV from the UV image.
COPY --from=ghcr.io/astral-sh/uv:latest --chown=${UID}:${UID} /uv /uvx /bin/

# Create the app directory.
RUN mkdir /app
RUN chown -R ${UID}:${UID} /app

# Set the working directory inside the container.
WORKDIR /app

# Copy the Django project to the container.
ADD ./music_space /app/music_space
COPY ./pyproject.toml ./manage.py ./README.md /app/

# Run this command to synchronize all dependencies.
RUN ["/bin/uv", "sync", "--no-cache", "--dev", "--no-group", "prod"]

# Expose the Django port.
EXPOSE ${PORT}

# Change the user.
# USER backend:backend -> Failed canonicalization of Python.

# Run Django’s development server.
CMD ["uv", "run", "--no-cache", "--dev", "--no-group", "prod", "music-space", "runserver", "0.0.0.0:${PORT}"]
